version: '3'
services:
  app:
    container_name: lamp_php
    build:
      context: ./php
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${PWD}/php:/var/www/html
    ports:
      - "80:80"
    network_mode: "lamp-network"

  db1:
    container_name: lamp_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    env_file:
      - mysql.env
    ports:
      - "13306:3306"
    volumes:
      # 設定ファイルを同期
      - ./mysql/mysql_conf:/etc/mysql/conf.d
      # dockerコンテナを起動したき時「docker-entrypoint-initdb.d」にあるSQL文を実行してくれる
      - ./mysql/mysql_init:/docker-entrypoint-initdb.d
      # データを同期
      - ./mysql/mysql_data:/var/lib/mysql
    network_mode: "lamp-network"

networks:
  lamp-network:
